name = "Calva"
license = "MIT"
licenselink = "https://github.com/juanwolf/calva/blob/master/LICENSE"
description = "A simple theme for your blog with no JS involved."
homepage = "http://juanwolf.fr/"
tags = ["blog", "perso", "minimal"]
features = ["org", "blog"]
min_version = "0.41"

[author]
  name = "juanwolf"
  homepage = "https://juanwolf.fr"
